# Generated by Django 5.2.9 on 2025-12-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_alter_siteconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(default='India', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='disclaimer',
            field=models.TextField(blank=True, default='Product color may slightly vary due to photographic lighting or your device settings.'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_address',
            field=models.TextField(blank=True, default='Andhra Pradesh, India'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_name',
            field=models.CharField(blank=True, default='VINSARAA', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
