# Generated by Django 5.2.9 on 2025-12-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_country_of_origin_product_disclaimer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='video_url',
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a product video (MP4/WebM)', null=True, upload_to='product_videos/'),
        ),
    ]
