# Generated by Django 5.2.9 on 2025-12-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_productimage_options_remove_product_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='disclaimer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='wash_care',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
