# Generated by Django 5.2.9 on 2025-12-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videosection',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hero_slides/'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='videosection',
            name='video_url',
            field=models.URLField(default='https://your-default-video.mp4'),
        ),
    ]
