# Generated by Django 5.2.9 on 2025-12-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_content', '0002_remove_videosection_thumbnail_alter_heroslide_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videosection',
            name='video_url',
        ),
        migrations.AddField(
            model_name='videosection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videosection',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
