# Generated by Django 5.2.9 on 2025-12-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_content', '0003_remove_videosection_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosection',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Paste full YouTube URL here', null=True),
        ),
    ]
