# Generated by Django 5.2.9 on 2025-12-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_savedaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedaddress',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='savedaddress',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
